# Generated by Django 4.1 on 2022-12-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firName", models.CharField(max_length=30, verbose_name="Имя")),
                ("secName", models.CharField(max_length=50, verbose_name="Фамилия")),
                ("login", models.CharField(max_length=30, verbose_name="Логин")),
                ("password", models.CharField(max_length=30, verbose_name="Пароль")),
            ],
        ),
    ]
