# Generated by Django 4.1 on 2023-01-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_profile_delete_rega"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MainPage",
            new_name="Post",
        ),
    ]
